services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moplus-server-dev
    restart: always
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env.dev
    depends_on:
      - mysql
    networks:
      - moplus
      - nginx-network

  mysql:
    image: mysql:8.0
    container_name: moplus-mysql-dev
    env_file:
      - .env.dev
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - moplus
volumes:
  mysql_data:

networks:
  moplus:
    driver: bridge
  nginx-network:
    external: true