services:
  back:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: moplus-server-prod
    image: moplus-server-prod
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env.prod
    depends_on:
      - mysql
    networks:
      - moplus-prod
      - nginx-network

  mysql:
    image: mysql:8.0
    container_name: moplus-mysql-prod
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - moplus_prod_data:/var/lib/mysql
    networks:
      - moplus-prod
volumes:
  moplus_prod_data:

networks:
  moplus-prod:
    driver: bridge
  nginx-network:
    external: true