spring:
  profiles:
    active: local
    group:
      local: "local, datasource"
      dev: "dev, datasource"

sentry:
  dsn: ${SENTRY_DSN}
  enable-tracing: true
  tracesSampleRate: 1.0
  debug: true
  environment: local
