spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3307/${DEV_MYSQL_DATABASE}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DEV_MYSQL_PASSWORD}
    username: ${DEV_MYSQL_USER}
    hikari:
      maximum-pool-size: 10 # default
      connection-timeout: 3000 # 30 seconds in milliseconds
      keepalive-time: 600000 # 5 minutes in milliseconds

logging:
  level:
    root: ERROR