spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_HOST}:3306/${DEV_MYSQL_DATABASE}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DEV_MYSQL_PASSWORD}
    username: ${DEV_MYSQL_USERNAME}
    hikari:
      maximum-pool-size: 10 # default
      connection-timeout: 3000 # 30 seconds in milliseconds
      keepalive-time: 600000 # 5 minutes in milliseconds

logging:
  level:
    root: ERROR