spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update

sentry:
  dsn: ${SENTRY_DSN}
  enable-tracing: true
  tracesSampleRate: 1.0
  debug: true
  environment: dev


