spring:
  profiles:
    active: ${profile}
    group:
      local: "local, datasource"
      dev: "dev"
      prod: "prod"
    include:
      - aws
      - security
      - monitoring
  mvc:
    ignore-default-favicon: true

cors-allowed-origins:
  http://localhost:8080,
  http://localhost:3000,